# Generated by Django 4.0.6 on 2022-09-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motivations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='motivation',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
