# Generated by Django 4.0.6 on 2022-09-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motivations', '0002_motivation_is_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motivation',
            name='nickname',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
