# Generated by Django 4.0.6 on 2022-09-02 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motivations', '0003_alter_motivation_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motivation',
            name='nickname',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
